- backend/package.json
- backend/src/app.module.ts
- backend/src/config/configuration.ts
- backend/src/config/typeorm.config.ts
- backend/src/entities/board.entity.ts
- backend/src/entities/bookmark.entity.ts
- backend/src/entities/category.entity.ts
- backend/src/entities/comment.entity.ts
- backend/src/entities/diary.category.entity.ts
- backend/src/entities/diary.stat.category.entity.ts
- backend/src/entities/diary.stat.entity.ts
- backend/src/entities/dream.diary.entity.ts
- backend/src/entities/favorite.entity.ts
- backend/src/entities/follow.entity.ts
- backend/src/entities/oauth.entity.ts
- backend/src/entities/user.entity.ts
- backend/src/enum/board.type.ts
- backend/src/enum/disclosure.scope.type.ts
- backend/src/enum/filter.type.ts
- backend/src/enum/provider.type.ts
- backend/yarn.lock
TypeORM에 entity를 매핑하고 DB 연결이 되는 것을 확인했습니다.
작업은 백엔드 팀원 전체가 화면 공유를 통해 진행했습니다!
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/11
> [BE] ORM 매핑 및 DB 연동

- backend/package.json
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/jwt/jwt.strategy.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
- backend/yarn.lock
첫 로그인 후 유저의 정보를 DB에 저장하는 부분을 추가했습니다.
또한 기존에 Mocking용으로 사용했던 `MockUserService`와 `IUserService`는 이제 DB 연동이 이루어졌으므로 삭제하였습니다!
User와 OAuth 테이블에 저장하는 과정은 하나의 트랜잭션으로 묶어서 구현했습니다.
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/5
> [BE] FEAT: 유저 정보를 DB에 저장하는 기능 추가

- backend/src/auth/auth.service.ts
- backend/src/user/user.service.ts
로그인 시도 시, 이슈에서 남겼던 사진과 같이 500번대 에러가 발생하며 로그인에 실패하는 버그를 수정했습니다.
원인은 `findOrCreateUserBySocialProfile` 메소드에서 이미 유저가 존재하는 경우 `User` 엔티티 객체를 리턴하고,
이 객체를 `jwtService.sign(user)` 와 같은 방식으로 토큰 생성을 시도했기 때문입니다.
`jwtService.sign()`의 인자로는 `plain object`(특정 클래스의 인스턴스로 만든 것이 아닌 curly braces({})로 프로퍼티와 값만 갖는 object)를 넣어야합니다..!
따라서
```
this.jwtService.sign({
userId: user.userId,
nickname: user.nickname,
imageUrl: user.imageUrl,
});
```
와 같은 방식으로 수정하니 정상적으로 토큰이 발행되었습니다!
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/18
> [BE] BUG: 토큰 생성 시 에러 발생 수정

- frontend/src/components/common/HeaderBar.vue
- frontend/src/components/icons/IconGoBack.vue
- frontend/src/router/index.ts
- frontend/src/views/FollowView.vue
- frontend/src/views/GenerateImageView.vue
헤더바에 뒤로가기 버튼을 아래 라우트에 한해서 활성화도록 기능을 추가하였습니다.
'dream-diary',
'new-dream-diary',
'generate-image',
'board',
'new-board',
'comment',
'profile',
'profile-edit',
'follow',
'bookmark',
'like',
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/31
> [FE] FEAT: 헤더바에 뒤로가기 버튼 조건부 추가

- backend/src/main.ts
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/34
> [BE] BUG: FE_HOST CORS 정책 예외 추가

- .gitignore
- backend/package.json
- backend/src/app.module.ts
- backend/src/config/configuration.ts
- backend/src/dto/profile.update.request.dto.ts
- backend/src/profile/profile.controller.ts
- backend/src/profile/profile.service.ts
- backend/yarn.lock
formData 업로드 방식을 UseInterceptors 를 이용하는 방식으로 바꾼 코드입니다.
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/39
> [BE] FIX: 프로필 업데이트 이미지 업로드 로직 수정

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
자기 자신의 정보를 조회하는 API 추가했습니다. 너무 짜잘해서 따로 리뷰는 없이 머지하겠습니다..!
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/43
> [BE] FEAT: 자기 자신의 정보를 조회하는 API 추가

- backend/src/profile/profile.controller.ts
formData 업로드에서 이미지 url의 앞부분에 로컬 서버 주소를 추가하여 이미지 url 을 저장하도록 코드를 수정하였습니다.
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/#39
> [BE] FIX: 프로필 수정 이미지 URL 변경 - 서버주소 추가

- backend/src/dto/follow.user.dto.ts
- backend/src/dto/follow.user.response.dto.ts
- backend/src/profile/profile.controller.ts
- backend/src/profile/profile.service.ts
1. 팔로우/언팔로우 기능의 API를 구현하였습니다
2. 프로필에서 해당 유저의 팔로잉 목록 및 팔로워 목록 조회 시 로그인한 유저의 팔로우 여부 및 해당 유저이 정보를 반환하는 API 를 구현하였습니다.
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/48
> [BE] FEAT: 팔로우 기능 관련 API 구현

- backend/src/profile/profile.controller.ts
- backend/src/profile/profile.service.ts
- frontend/src/api/axios.custom.ts
- frontend/src/views/FollowView.vue
> [COMMON] FIX: 팔로우 목록 관련 버그 수정 #41

- backend/src/comment/comment.controller.ts
- backend/src/comment/comment.service.ts
- backend/src/dto/comment.dto.ts
- backend/src/dto/comment.response.dto.ts
- backend/src/dto/comment.user.response.dto.ts
- backend/src/entities/comment.entity.ts
- mariadb/dalle.sql
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/63
> [BE] FIX: 댓글 조회 응답에 유저정보 추가

- frontend/src/App.vue
- frontend/src/components/common/HeaderBar.vue
- frontend/src/router/index.ts
- frontend/src/views/BoardListView.vue
- frontend/src/views/DreamDiaryFeedView.vue
- frontend/src/views/DreamDiaryView.vue
- frontend/src/views/PostView.vue
#60번째에서 오류인 부분 수정해서 pr에 올렸습니다. 목록 별 상세페이지를 구현할 예정이며 상세페이지 구현이 완료되면 좋아요와 북마크 뷰를 구현할 예정입니다.
> [FE] FIX:보드목록,꿈일기목록 수정 

- frontend/src/App.vue
- frontend/src/components/common/HeaderBar.vue
- frontend/src/router/index.ts
- frontend/src/views/BoardListView.vue
- frontend/src/views/DreamDiaryFeedView.vue
- frontend/src/views/DreamDiaryView.vue
- frontend/src/views/PostView.vue
> [FE] FEAT : 꿈일기 목록 뷰와 게시글 목록 뷰에서 게시글 작성 뷰로 넘어가는 버튼 추가

- frontend/src/api/axios.custom.ts
- frontend/src/views/CommentView.vue
댓글 API 변경사항을 반영했습니다. (댓글 목록 조회 시, 유저의 닉네임과 프로필 이미지 url을 같이 받아오도록 수정)
댓글 입력칸 css를 개선했습니다. (pc화면에서도 댓글 입력칸이 가상 모바일 스크린 안에서만 생기도록 수정)
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/56
> [FE] 댓글 API 변경사항 반영

- .github/workflows/be_cicd.yaml
- .github/workflows/fe_cicd.yaml
- backend/src/app.module.ts
> [ETC] app module에 env 파일 경로 추가 & cd 워크플로우 설정

- .github/workflows/be_cicd.yaml
- .github/workflows/fe_cicd.yaml
> dev to main

- .github/workflows/be_cicd.yaml
- .github/workflows/fe_cicd.yaml
> [ETC] cd config 수정

- backend/nest-cli.json
> [BE] FIX: nest-cli 수정

- frontend/src/views/CommentView.vue
댓글 목록에서 답글이 댓글 밑에 달리도록 수정했습니다.
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/86
> [FE] 댓글 목록에서 답글이 댓글 밑에 달리도록 수정

- backend/src/app.module.ts
- backend/src/board/board.controller.ts
- backend/src/dreamdiary/dreamdiary.controller.ts
- backend/src/profile/profile.controller.ts
> [BE] FIX: 이미지 업로드 경로 수정

- mariadb/dalle.sql
> [BE] FIX: follow table pk 제약 조건 수정

- backend/src/config/configuration.ts
- backend/src/dreamdiary/dreamdiary.service.ts
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/22
> [BE} FEAT: 꿈일기 기본 이미지 저장 추가

- frontend/src/components/common/LoadingAnimation.vue
- frontend/src/router/index.ts
- frontend/src/views/FollowView.vue
- frontend/src/views/GenerateImageView.vue
일기 이미지 생성 시, 로딩 애니메이션 추가 & 팔로우 탭 선택을 param으로 구분하지 않도록 수정
https://github.com/CSID-DGU/2023-1-OSSP2-DALL-E-noway-2/issues/96
> [FE] FIX: 기타 개선사항 반영

- backend/src/app.module.ts
> [BE] serve static 경로 오류 수정

- .github/workflows/be_cicd.yaml
- backend/package.json
- backend/src/app.module.ts
> [BE] 이미지 경로 오류 최종 수정
